server:
  port: 9696
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eyjafjallajokull-Roman/config-server
          clone-on-start: true
